version: "2.1"
executors:
  node-executor:
    docker:
      - image: circleci/node:14
jobs:
  deploy-netlify:
    executor: node-executor
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Run build
          command: yarn build
      - run:
          name: Netlify Deploy
          command: yarn deploy-netlify

workflows:
  deploy:
    jobs:
      - deploy-netlify:
          filters:
            branches:
              only: main
